# Author: Nicholas Stroustrup
# Edits: Cody Jarrett

# This file builds Lifespan Machine worm detection model files
# using the R programming language bindings to libsvm

# The base_analysis_dir variable should be set to the absolute path
# of the analysis files generated by the worm browser
# (see worm detection model generation instructions).

# The features_file should be set to the relative pathname
# of the model file you want to generate.

# The worm detection model file is written to the same directory as the
# input files, and some diagnostic data is plotted.

library("e1071")
library(rgl)
library("ranger")

base_analysis_dir <- "/home/cody/Desktop/analysis"
features_file <- "training_sets/high_24_plus_fscore_features"

# .5 means equal weighting.
# Values closer to 1 reduce false-negatives and increase false positives
prefer_false_positives <- .75

read_svm_format <- function(filename, features_filename = "") {
    # Function to load in SVM feature files generated by the lifespan machine
    raw <- read.table(filename, header = FALSE, sep = " ")

    if (!any(!is.na(raw[, dim(raw)[2]]))) {
        raw <- raw[, 1:(dim(raw)[2] - 1)]
    }

    feature_values <- as.data.frame(apply(
        raw,
        c(1, 2),
        function(x) as.numeric(sub(".*:", "", x))
    ))

    feature_indicies <- as.numeric(apply(
        raw[1, 2:(dim(raw)[2])],
        1,
        function(x) as.numeric(sub(":.*", "", x))
    ))

    if (features_filename != "") {
        feature_name_lookup <- read.table(features_filename,
            header = FALSE,
            sep = "\t"
        )

        # The plus one is because the lifespan machine source code is offset
        # from 1 compared to the feature numbers sent to libSVM
        idx <- match(feature_indicies, feature_name_lookup$V1 + 1)

        features <- as.character(feature_name_lookup$V2[idx])
    } else {
        features <- unlist(lapply(
            1:(dim(feature_values)[2] - 1),
            function(x) paste0("f", x)
        ))
    }

    names(feature_values) <- c("is_a_worm", features)

    return(list(features = feature_values, feature_names = feature_name_lookup))
}

load_train_test_data <- function() {
    # Load train and test data from disk
    if (!exists("train_set")) {
        ts <- read_svm_format(
            paste0(features_file, "_test.txt"),
            paste0(features_file, "_included_stats.txt")
        )

        test_set <- ts[["features"]]
        feature_names <- ts[["feature_names"]]

        train_set <- read_svm_format(
            paste0(features_file, "_train.txt"),
            paste0(features_file, "_included_stats.txt")
        )[["features"]]
    }

    return(list(
        "test_set" = test_set,
        "train_set" = train_set,
        "feature_names" = feature_names
    ))
}

print_acc_and_confusion <- function(model_name, accuracy, confusion) {
    rownames(confusion) <- c("Not Worm", "Worm")
    colnames(confusion) <- c("Not Worm", "Worm")

    print(paste(model_name, "Accuracy:", accuracy))
    print(paste(model_name, "Confusion Matrix:"))

    print(confusion)
}

build_svm_model <- function(train_set, test_set) {
    # Build the SVM worm detection model
    model <- svm(is_a_worm ~ .,
        data = train_set,
        kernel = "radial",
        type = "C-classification",
        gamma = .7,
        cost = 20,
        scale = FALSE,
        probability = FALSE,
        class.weights = c(
            "1" = prefer_false_positives,
            "-1" = 1 - prefer_false_positives
        )
    )

    pred <- predict(model, test_set)

    results <- table(
        pred = as.numeric(as.character(pred)) > 0,
        true = test_set[, 1]
    )

    fp <- which(
        as.numeric(
            as.character(pred)
        ) > 0 & as.numeric(as.character(test_set$is_a_worm)) < 0
    )

    fn <- which(
        as.numeric(
            as.character(pred)
        ) < 0 & as.numeric(as.character(test_set$is_a_worm)) > 0
    )

    accuracy <- (results[1, 1] + results[2, 2]) / sum(results)

    confusion <- results / sum(results)

    print_acc_and_confusion("SVM", accuracy, confusion)

    model_info <- list(
        "model" = model,
        "pred" = pred,
        "results" = results,
        "fp" = fp,
        "fn" = fn,
        "accuracy" = accuracy,
        "confusion" = confusion
    )

    return(model_info)
}

write_svm_model <- function(features_file,
                            svm_model,
                            feature_names) {
    # The package "e1071" disregards feature and label numbers,
    # so we need to reload and correct output files
    fname <- paste0(features_file, "_model_temp.txt")
    fname2 <- paste0(features_file, "_model.txt")

    write.svm(svm_model, svm.file = fname)

    fo <- unique(feature_names$V1[order(feature_names$V1)])
    line_num <- 0

    infile <- file(fname, "r")
    outfile <- file(fname2, "w")

    while (TRUE) {
        line <- readLines(infile, n = 1)

        if (length(line) == 0) {
            break
        }

        if (line_num == 6) {
            writeLines("label 1 -1", outfile)
        } else if (line_num < 9) {
            writeLines(line, outfile)
        } else {
            splt <- strsplit(line, " ")

            out <- paste0(splt[[1]][1], " ")

            poss <- attr(regexpr(".*:", splt[[1]]), "match.length")

            vals <- substring(
                splt[[1]][2:length(poss)],
                poss[2:length(poss)] + 1,
                1000
            )

            for (i in seq_along(vals)) {
                out <- paste0(out, fo[i] + 1, ":", vals[i], " ")
            }
            writeLines(out, outfile)
        }

        line_num <- line_num + 1
    }

    close(infile)
    close(outfile)
    file.remove(fname)
}

build_rf_model <- function(train_set, test_set) {
    # Build a Random Forest model to identify most useful features
    set.seed(71)

    train_set$is_a_worm <- as.factor(as.character(train_set$is_a_worm))

    model <- ranger(is_a_worm ~ .,
        data = train_set,
        importance = "impurity",
        num.trees = 1000,
        respect.unordered.factors = "ignore"
    )

    pred <- predict(model, data = test_set)

    results <- table(pred = pred$predictions, true = test_set[, 1])

    accuracy <- (results[1, 1] + results[2, 2]) / sum(results)

    confusion <- results / sum(results)

    print_acc_and_confusion("Random Forest", accuracy, confusion)

    rf_model_info <- list("model" = model)

    return(rf_model_info)
}

plot_most_useful_features <- function(rf_model, test_set) {
    par(mar = c(16, 2, 2, 2))

    v <- order(rf_model$variable.importance, decreasing = TRUE)

    vn <- names(rf_model$variable.importance)[v]

    plot(seq_along(v),
        rf_model$variable.importance[v],
        xaxt = "n",
        xlab = ""
    )

    vx <- as.numeric(v)

    axis(1, at = vx, labels = FALSE)

    text(
        x = vx,
        y = par()$usr[3] - 0.05 * (par()$usr[4] - par()$usr[3]),
        labels = as.character(vn),
        srt = 90,
        adj = 1,
        xpd = TRUE
    )
}

run_pca <- function(test_set) {
    m <- cov(test_set[2:(dim(test_set)[2])])
    pca_res <- prcomp(m, center = FALSE, scale. = FALSE)

    return(pca_res)
}

plot_3d_svm_results <- function(test_set, pca_res, svm_model_info) {
    # Plot worms and non-worms and overlay SVM mistakes
    base_size <- 2
    d <- as.matrix(test_set[, 2:(dim(test_set)[2])])
    tf <- d %*% pca_res$rotation
    cols <- c("green", "black", "red", "pink")
    col <- cols[2 - 1 * (test_set[, "is_a_worm"] > 0)]
    big <- rep(FALSE, length(col))
    col[svm_model_info$fp] <- cols[3]
    col[svm_model_info$fn] <- cols[4]
    big[svm_model_info$fp] <- TRUE
    big[svm_model_info$fn] <- TRUE

    plot3d(tf[!big, 1],
        tf[!big, 2],
        tf[!big, 3],
        col = col[!big],
        size = base_size,
        xlab = "PCV1",
        ylab = "PCV2",
        zlab = "PCV3"
    )

    legend3d("topright",
        legend = c("worms", "non-worms"),
        pch = 16,
        col = cols[1:2],
        inset = c(0.02)
    )

    points3d(tf[big, 1],
        tf[big, 2],
        tf[big, 3],
        col = col[big],
        size = base_size * 4
    )

    legend3d("topright",
        legend = c(
            "worms",
            "non-worms",
            "SVM false-positive",
            "SVM false-negative"
        ),
        pch = 16,
        col = cols,
        inset = c(0.02)
    )
}

main <- function() {
    setwd(base_analysis_dir)

    train_test_data <- load_train_test_data()

    train_set <- train_test_data$train_set
    test_set <- train_test_data$test_set

    svm_model_info <- build_svm_model(
        train_set,
        test_set
    )

    # Write the model to disk
    write_svm_model(
        features_file,
        svm_model_info$model,
        train_test_data$feature_names
    )

    # Write the prediction results file to disk (for additional diagnostics)
    write.table(svm_model_info$pred,
        file = paste0(
            features_file,
            "_results.txt"
        ),
        sep = " ",
        row.names = FALSE,
        col.names = FALSE,
        quote = FALSE
    )

    rf_model_info <- build_rf_model(train_set, test_set)

    plot_most_useful_features(rf_model_info$model, test_set)

    readline(prompt = "Press [enter] to continue")

    pca_res <- run_pca(test_set)

    plot(pca_res, type = "l")
    title("PCA Results")

    readline(prompt = "Press [enter] to continue")

    plot_3d_svm_results(test_set, pca_res, svm_model_info)
}

main()
